### ISSUE TITLE
DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH

### ISSUE THREAD

**Issue by agragregra** [shama/webpack-stream#240]
[DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)

please change [hash] to [fullhash] in index.js

**Comment by ZhyMC** [comment]
same issue

**Comment by shama** [comment]
Fixed with https://github.com/shama/webpack-stream/commit/2ff8a4ff1e49c96543201c28ab613a8646fb99a8#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L124 and then later no default `output.filename` is supplied to allow webpack to choose the output for this use case: https://github.com/shama/webpack-stream/pull/212
