### ISSUE TITLE
Stream in files to gulp-webpack

### ISSUE THREAD

**Issue by avanderhoorn** [shama/webpack-stream#3]
I was wondering if its possible to extend things so that one can stream in the files to gulp-webpack. Its just that I do some pre processing of the files outside of webpack and would prefer not to have to send them to disk before running webpack. This might require changes at webpacks end but not being intermit with how gulp works, I'm not sure where the change needs to go.

**Comment by Arnavion** [comment]
So people don't waste time on this like I just did, overriding compiler.inputFileSystem will not do anything. The webpack() function calls [`new NodeEnvironmentPlugin().apply(compiler);`](https://github.com/webpack/webpack/blob/e46e5cb/lib/webpack.js#L23) that then [sets up the resolvers to use the NodeJsInputFileSystem](https://github.com/webpack/webpack/blob/e46e5cb/lib/node/NodeEnvironmentPlugin.js#L16), so overriding compiler.inputFileSystem after the call to webpack() will not fix the resolvers. Then the whole compilation will fail because it will not find the files on disk.
