### ISSUE TITLE
Cannot keep source file sub-directories

### ISSUE THREAD

**Issue by sivan** [shama/webpack-stream#62]
I try to use webpack with `vinyl-name` to compile my scripts like the demo:
```js
var gulp = require('gulp');
var webpack = require('webpack-stream');
var named = require('vinyl-named');
gulp.task('default', function() {
  return gulp.src(['src/*.js', 'src/**/*.js'])
    .pipe(named())
    .pipe(webpack())
    .pipe(gulp.dest('dist/'));
});
```
But js files in `src/**` are compiled to the root directory in `dist/` like this:

 - src/base.js --> dist/base.js  // This is right
 - src/user/login.js --> dist/login.js // This should be in `dist/user/login.js`

How can I make it right?

**Comment by cmtt** [comment]
According to reported [issues](https://github.com/webpack/webpack/issues/1189), webpack does not support multiple output paths yet.

Nevertheless, there are some workarounds:

 - use webpack's output filename templates (this does not create the described directory structure)

````js
gulp.task('default', function() {
  return gulp.src(['src/*.js', 'src/**/*.js'])
    .pipe(named())
    .pipe(webpack({
      output : {
        filename : '[name]/[name].js'    
      }
    }))
    .pipe(gulp.dest('dist/'));
});
````

- hook into the stream with Gulp plugins and change the file's paths.

Apparently, you can use a combination of vinyl-named and gulp-rename in order to recreate the directory structure. You have to pipe your sources twice through gulp-rename, once for caching the  original directory of your input, once for restoring the cached attribute.

It is an ugly and questionable solution, but it should do the job as long as the webpack module isn't fixed.

````js
gulp.task('default', function() {
  var tmp = {};
  return gulp.src(['src/*.js', 'src/**/*.js'])
    .pipe(named())
    .pipe(rename(function (path) {
      tmp[path.basename] = path;
    }))    
    .pipe(webpack({
      output : {
        filename : '[name]/[name].js'    
      }
    }))
    .pipe(rename(function (path) {
      path.dirname = tmp[path.basename].dirname;
    }))    
    .pipe(gulp.dest('dist/'));
});
````

**Comment by sivan** [comment]
Thanks @cmtt , I'll have a try at the last example. :+1:

**Comment by shama** [comment]
Thanks for the help @cmtt!

**Comment by kevkehoe** [comment]
Realise this is an old post but I struggled for ages with this due to a complex path structure, duplicate file names and needing to use **gulp-filter** in my pipeline. Posting what worked for me here in case it helps anyone: 

```js
var gulp = require('gulp');
var path = require('path');
var webpack = require('webpack-stream');
var named = require('vinyl-named');

var config = {
  webpack: {
    output: {
      filename: '[name].js'
    },
    entry: {}
  }
};

function repath(target, removal, pathOnly) {
  return target.replace(removal, '')
    .replace(pathOnly ? /\.[^/.]+$/ : '', '')
    .replace(new RegExp('\\' + path.sep, 'g'), '/');
}

gulp.task('configure', function () {
  return gulp.src('src/scripts')
    .pipe(named(function (file) {
      config.webpack.entry[repath(file.path, file.base, true)]
        = '.' + repath(file.path, file.cwd);
      this.queue(file);
    }));
});

gulp.task('scripts', ['configure'], function() {
  return gulp.src('src/scripts')
    .pipe(webpack(config.webpack))
    .pipe(gulp.dest('dist/scripts'));
});

```

It's a case of building up the webpack config before running the plugin. The repath function is a bit messy but should make it env agnostic. **through2** works equally as well as **vinyl-named** but I am using named elsewhere so left it as that. Would have been nice to get it to work directly before webpack in the pipeline rather than as a task dep but I couldn't make it work.

:ghost:

**Comment by ljani** [comment]
@kevkehoe Thanks. There's one problem still though. When I'm browsing to eg. `http://localhost/area/index.html`, the common module is requested from `http://localhost/area/1.1.js` instead of `http://localhost/1.1.js` where it actually lives. I could tweak my server, but I'd prefer if webpack knew about the relative path. Have you experienced similar problems? Anyway, I guess this is a problem of webpack in the end.

**Comment by asika32764** [comment]
[vinyl-named-with-path](https://www.npmjs.com/package/vinyl-named-with-path) can solve my issue.

```js
var gulp = require('gulp');
var webpack = require('webpack-stream');
var named = require('vinyl-named-with-path');
gulp.task('default', function() {
  return gulp.src(['src/**/*.js'])
    .pipe(named())
    .pipe(webpack())
    .pipe(gulp.dest('dist/'));
});
```
